### ISSUE TITLE
[Feature Suggestion] Alternative Video Conferencing

### ISSUE THREAD

**Issue by raveesh-me** [sbis04/events_demo#1]
Amazing and very practical project!

Some organizations prefer to schedule video meeting via alternative video conferencing platforms like zoom or jitsi meet. There are plugins for these for the google calendar platform. Is something like plugin discovery or alternate discovery available in the calendar API?

**Comment by sbis04** [comment]
I don't think so. The **Calendar API** only allows the creation and sharing of **Google Meet** video conference link. There is no option to insert any other custom link in that field explicitly. 

More info about the Calendar API here: http://googleapis.github.io/google-api-python-client/docs/dyn/calendar_v3.html
